name: fitness_app
description: "Fitness application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0
  shared_preferences: ^2.5.5
  flutter_bloc: ^9.1.1
  dio: ^5.9.2
  dartz: ^0.10.1
  json_annotation: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.12.0
  flutter_gen_runner:

  flutter_lints: ^6.0.0
  json_serializable: ^6.14.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/



  fonts:
     - family: Lexend
       fonts:
         - asset: assets/fonts/Lexend-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


flutter_gen:
  output: lib/core/gen/

  # Optional
  integrations:
    image: true
    flutter_svg: true